Remove separate sketch file from We_Buttton example
Previously, the We_Buttton example folder contained two complete sketches: We_Buttton.ino and We_EncoderMotor.ino. This caused compilation to fail:

E:\electronics\arduino\libraries\Weeemake\examples\We_Buttton\We_EncoderMotor.ino: In function 'void setup()':

We_EncoderMotor:5:6: error: redefinition of 'void setup()'

 void setup()

      ^~~~~

E:\electronics\arduino\libraries\Weeemake\examples\We_Buttton\We_Buttton.ino:4:6: note: 'void setup()' previously defined here

 void setup()

      ^~~~~

E:\electronics\arduino\libraries\Weeemake\examples\We_Buttton\We_EncoderMotor.ino: In function 'void loop()':

We_EncoderMotor:12:6: error: redefinition of 'void loop()'

 void loop()

      ^~~~

E:\electronics\arduino\libraries\Weeemake\examples\We_Buttton\We_Buttton.ino:8:6: note: 'void loop()' previously defined here

 void loop()

      ^~~~

It's unclear to me what should be done with We_EncoderMotor.ino, since the library already contains a "We_EncodeMotor" and a "We_EncoderMotor" example sketches and each of these sketches is somewhat similar, yet different. So I'm just deleting the thing.